services:
  postgres:
    image: postgres
    restart: always

    environment:
#    - POSTGRES_DB=auctions
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgrespw
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postresql/data
  mongodb:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=mongopw
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - mongodata:/var/lib/mongodb/data  
    

volumes:
    pgdata:   
    mongodata:    
  